[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r backend/chat2api/requirements.txt"]

[phases.build]
cmds = ["echo 'No build phase needed for Python backend'"]

[start]
cmd = "cd backend/chat2api && uvicorn main:app --host 0.0.0.0 --port $PORT"
