[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend/chat2api && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksConfig]
providers = ["python"]
