// Industry name to ID mapping for navigation
export const getIndustryIdFromName = (industryName: string): string => {
  const industryMap: { [key: string]: string } = {
    // Direct matches
    'Technology': 'tech',
    'Healthcare': 'healthcare',
    'Business': 'business',
    'Finance': 'finance',
    'Marketing': 'marketing',
    'Education': 'education',
    'Creative Arts': 'creative',
    'Engineering': 'engineering',
    'Science': 'science',
    'Legal': 'legal',
    'Government': 'government',
    'Non-Profit': 'nonprofit',
    'Skilled Trades': 'trades',
    'Hospitality': 'hospitality',
    'Media & Entertainment': 'media',
    'Digital Creator': 'digital-creator',
    'Public Service': 'public-service',
    'Sanitation & Maintenance': 'sanitation',
    'Military & Defense': 'military',
    'Music & Audio': 'music',
    'Gaming & Casino': 'gaming-casino',
    'Transportation & Logistics': 'transportation',
    'Retail & Sales': 'retail',
    'Agriculture & Food': 'agriculture',
    'Construction & Real Estate': 'construction',
    'Specialized Trades': 'specialized-trades',
    'Drones & Aviation': 'drones-aviation',
    'Marine Science': 'marine-science',
    'Investment & Finance': 'investment-finance',
    'Middle Management': 'middle-management',
    'Real Estate': 'real-estate',
    'Emerging Technology': 'emerging-tech',
    'Environmental Science': 'environmental',
    'Space & Aerospace': 'space-aerospace',
    
    // Alternative names and common variations
    'Traditional Retail': 'retail',
    'Print Media': 'media',
    'Coal Mining': 'trades',
    'Telemarketing': 'business',
    'Manufacturing': 'trades',
    'Retail': 'retail',
    'Media': 'media',
    'Trades': 'trades',
    'Tech': 'tech',
    'Creative': 'creative',
    'Nonprofit': 'nonprofit',
    'Entertainment': 'media',
    'Digital': 'digital-creator',
    'Public': 'public-service',
    'Sanitation': 'sanitation',
    'Military': 'military',
    'Music': 'music',
    'Gaming': 'gaming-casino',
    'Transportation': 'transportation',
    'Agriculture': 'agriculture',
    'Construction': 'construction',
    'Aviation': 'drones-aviation',
    'Marine': 'marine-science',
    'Investment': 'investment-finance',
    'Management': 'middle-management',
    'Emerging Tech': 'emerging-tech',
    'Environmental': 'environmental',
    'Space': 'space-aerospace',
    'Aerospace': 'space-aerospace'
  };
  
  return industryMap[industryName] || 'tech'; // Default to tech if not found
};
